title: Tim
author: Tim
email: ridenowhere90@gmail.com
description:
  Java, Web 개발자 Tim의 포트폴리오와 블로그입니다.
#baseurl: # the subpath of your site, e.g. /blog
url: https://majortim.github.io #"" the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: majortim
tistory: 
  username: majortim
  description: Tim's Tistory
header_pages:
  # - about.md
  - projects.md
  - posts.md
lang: ko
show_excerpts:  true

# Build settings
encoding: utf-8
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
kramdown:
  auto_ids          : true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include: [".well-known"]
